### PR TITLE
Corrected callbacks for listing projects

### PR DESCRIPTION
**Pull request by rhodgkins**
Hello!

I found a few issues with the paginated APIs and handling of errors compared the the rest of the API.

I've not used coffee script before so I hope looks right - all the tests pass :)

Thanks for creating this library!

### CODE REVIEW

**Comment by rhodgkins** [comment]
Also I'm not really sure if the rest of the API passes errors through:

```
  show: (userId, fn = null) =>
    @debug "Users::show()"
    @get "users/#{parseInt userId}", (data) => fn data if fn
```

Should that just be:

```
  show: (userId, fn = null) =>
    @debug "Users::show()"
    @get "users/#{parseInt userId}", fn
```

?

**Comment by dave-irvine** [comment]
I'd stick with

```
(data) => fn data if fn
```

Or at the very least

```
fn if fn
```

else you risk calling a null.

**Comment by dave-irvine** [comment]
It will take me a while to review this as you're touching a lot of files at the same time, but thanks for your contribution :)

**Comment by rhodgkins** [comment]
> I'd stick with
>
> `(data) => fn data if fn`

Doesn't that then override the arity check in [`fn_wrapper`](https://github.com/node-gitlab/node-gitlab/blob/develop/src/ApiBaseHTTP.coffee#L41) as then all callbacks will ever only have an arity of 1?

Could `fn_wrapper` take care of the `null` check so it can be done in one place?

Understood about the review, no probs :+1:

**Comment by dave-irvine** [comment]
Looks like a long standing bug then :)

I think if you change it so that things start getting called with their proper arity we might have to bump major as that could be a breaking change for the implementations expecting an arity of 1 as it has historically been. @moul any thoughts here?

More and more I really need to find the time to do an ES6 rewrite.

**Comment by moul** [comment]
I like the idea, but I also prefer to keep the current implementation for this version and focus on the new ES6 version with all those ideas

**Pull request closed without merging**
